# Jekyll configuration

# Site settings
locale: "en-US"
title: "Aravind Iyer"
title_separator: "-"
name: "Aravind Iyer"
description: "Aravind Iyer, a tech guy, a scientist and computer engineer by training, writing about music, life and personal stuff."
url: https://www.aravindiyer.com
words_per_minute: 200
theme: "minimal-mistakes-jekyll"

# Comment hosting from Disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "aravindiyer"

# Comment hosting from Staticman
repository: "iyeraravind/aravind-website"
#comments:
#  provider: "staticman_v2"
#staticman:
#  branch: "master"
reCaptcha:
  siteKey: "6LfarVQUAAAAAOBAfH7NHqlBeI0sAx7jB7CcNp2u"
  secret: "6LfarVQUAAAAAHkHMLwfiOPFVwhLlygWiJ67Ub1w"

# Site search from Algolia
search: true
search_provider: "algolia"
algolia:
  application_id: 5XQCQN167D
  index_name: ARAVIND_WEBSITE
  search_only_api_key: 5c1ac82194add16945031972f23d08f7
  powered_by: "true"
  files_to_exclude:
    - _pages/blog.markdown
    - _pages/home.markdown
    - _pages/music-naka.markdown
    - _pages/only-human.markdown
    - _pages/sitemap.markdown
    - _drafts/*.markdown

# SEO and Analytics
bing_site_verification   : "EB2419D7F9B094E998F87C560BAE12C8"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-115949882-1"

# Social profile
twitter:
  username: "aravindiyer"
facebook:
  username: "aravindiyer"
  app_id: "2013161692342257"
og_image: "/assets/images/self-sketch-splash.jpg"
social:
  type: "Person"
  name: "Aravind Iyer"
  links:
    - "https://twitter.com/aravindiyer"
    - "https://facebook.com/aravindiyer"
    - "https://medium.com/@.aravindiyer"
    - "https://www.linkedin.com/in/aravindiyer"
    - "https://instagram.com/aravind.iyer"
    - "https://plus.google.com/+AravindIyer"

# Site author
author:
  name: "Aravind Iyer"
  avatar: "/assets/images/profile.jpg"
  bio: "A tech guy writing about music and life."
  location: "Bengaluru, India"
  uri: "https://www.aravindiyer.com"
  facebook: "aravindiyer"
  github: "iyeraravind"
  google_plus: "+AravindIyer"
  medium: ".aravindiyer"
  instagram: "aravind.iyer"
  linkedin: "aravindiyer"
  twitter: "aravindiyer"

# File reading
include:
  - _pages
  - _redirects
exclude:
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Gemfile
  - node_modules
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Jekyll processing
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Miscellaneous
permalink: /:categories/:title/
timezone: Asia/Kolkata # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-algolia
  - jemoji

# Collections - enable a collection for use as drafts
collections:
  drafts: 
    output: true
    permalink: /:categories/:title/
  music-naka:
    output: true
    permalink: /:categories/:title/
  only-human:
    output: true
    permalink: /:categories/:title/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Image assets folder
imagefolder: "/assets/images/"

# Build settings
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _drafts
  - scope:
      path: ""
      type: drafts
    values:
      layout: draft
      author_profile: true
      read_time: true
      sitemap: false
      noindex: true   #To hide from robots and crawlers
  # _music-naka
  - scope:
      path: ""
      type: music-naka
    values:
      layout: article
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _only-human
  - scope:
      path: ""
      type: only-human
    values:
      layout: article
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
